import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { AuthProvider } from './shared/auth/AuthContext.jsx';
import App from './App.jsx';
import './styles/index.css';
import './styles/dark-contrast-fixes.css';
import './styles/panel-density.css';
import './styles/operations-button-fix.css';
ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><AuthProvider><App/></AuthProvider></BrowserRouter></React.StrictMode>);