import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { AuthProvider } from './shared/auth/AuthContext.jsx';
import App from './App.jsx';
import './styles/index.css';
import './styles/dark-contrast-fixes.css';
import './styles/panel-density.css';
import './styles/operations-button-fix.css';
import './styles/students-table.css';
import './styles/institutional-theme-tokens.css';
import './styles/institutional-theme-shell.css';
import './styles/institutional-theme-components.css';
import './styles/enrollments-mobile-fixes.css';
import './styles/admission-leads-fixes.css';
import './styles/public-admissions-fixes.css';
import './styles/public-admissions-contact-fixes.css';
import './styles/institutional-theme-dark.css';
import './styles/public-home-theme.css';
ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><AuthProvider><App/></AuthProvider></BrowserRouter></React.StrictMode>);